### ISSUE TITLE
CLI more options 

### ISSUE THREAD

**Issue by medeepaksaini** [jaywcjlove/svgtofont#48]
Hey @jaywcjlove @btmurrell , can someone help me how i  can modify npm cli command `svgtofont --sources build/icons/svg --output ./font --fontName icons` to get only font and less file not other files.

**Comment by jaywcjlove** [comment]
@medeepaksaini The configuration is added to package.json. Like this:


```json
{
  ....
  "svgtofont": {
     "css": false
  }
}
```

Upgrade `+ svgtofont@3.2.0`

**Comment by medeepaksaini** [comment]
@jaywcjlove and what about if i want to get only `scss` file and basic font files not `react` file Or Other file.

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/svgtofont/blob/3195dd6fc5c7c888241571a0100736b0efd3e41a/src/utils.ts#L197-L204

@medeepaksaini I need to modify the [copy-template-dir](https://www.npmjs.com/package/copy-template-dir), which will take some time.

**Comment by medeepaksaini** [comment]
Okay, Thanks 🙂👍

**Comment by jaywcjlove** [comment]
@medeepaksaini You can delete unnecessary files after generation. Can use [rimraf](https://www.npmjs.com/package/rimraf), Support CLI.

**Comment by medeepaksaini** [comment]
Okay

**Comment by medeepaksaini** [comment]
@jaywcjlove how i can change css file location ?

**Comment by jaywcjlove** [comment]
@medeepaksaini Can use [move-file-cli](https://www.npmjs.com/package/move-file-cli)

**Comment by jaywcjlove** [comment]
@medeepaksaini Upgrade `+ svgtofont@3.3.0`

```js
"svgtofont": {
  "website": false,
  "css": {
    "output": "css",
    "include": "\\.(css|less)$"
  }
},
```

**Comment by claudiuTicu** [comment]
Hi @jaywcjlove, great plugin, very useful i have a few questions:

for the css options, used like this:
`"svgtofont": {
    "website": false,
    "css": {
      "output": "./src/scss/components/",
      "include": "\\.(scss)$"
    },
    "emptyDist": true
  },,`

is there any way to specify the path for the generated fonts? 

currently it is generated like this: 
`@font-face {font-family: "icons";
  src: url('icons.eot?t=1607280845895'); /* IE9*/
  src: url('icons.eot?t=1607280845895#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url("icons.woff2?t=1607280845895") format("woff2"),
  url("icons.woff?t=1607280845895") format("woff"),
  url('icons.ttf?t=1607280845895') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('icons.svg?t=1607280845895#icons') format('svg'); /* iOS 4.1- */
}`

but i would need to generate them with a specific path, something like this:

`@font-face {font-family: "icons";
  src: url('../fonts/icons/icons.eot?t=1607280845895'); /* IE9*/
  src: url('../fonts/icons/icons.eot?t=1607280845895#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url("../fonts/icons/icons.woff2?t=1607280845895") format("woff2"),
  url("../fonts/icons/icons.woff?t=1607280845895") format("woff"),
  url('../fonts/icons/icons.ttf?t=1607280845895') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('../fonts/icons/icons.svg?t=1607280845895#icons') format('svg'); /* iOS 4.1- */
}`

also, is there any way to specify the name of the  output scss file? lets say i want to name it "_icons.scss" instead of "icons.scss" how is generated now. 

Thank you in advance.

**Comment by jaywcjlove** [comment]
@claudiuTicu 

```js
"svgtofont": {
  "fontName": "icons",
  "website": false,
  "css": {
    "output": "./src/scss/components/",
    "cssPath": "../fonts/icons/",
    "include": "\\.(scss)$"
  },
  "emptyDist": true
},
```


```diff
"svgtofont": {
+  "fontName": "icons",
  "website": false,
  "css": {
    "output": "./src/scss/components/",
+    "cssPath": "../fonts/icons/",
    "include": "\\.(scss)$"
  },
  "emptyDist": true
},
```

**Comment by claudiuTicu** [comment]
Hi @jaywcjlove , 
Thank you for your quick answer the `cssPath` option woks perfectly, very nice,  but regarding the `fontName` option, this one will rename all the files (font files) and also the class inside of scss.

I was expecting to have something like:
`"svgtofont": {
  "fontName": "icons",
  "website": false,
  "css": {
    "output": "./src/scss/components/",
+    "cssName": "_icons",
    "include": "\\.(scss)$"
  },
  "emptyDist": true
},`

which will output the `_icons.scss` file

**Comment by jaywcjlove** [comment]
@claudiuTicu Upgrade `+ svgtofont@3.6.0`


```diff
"svgtofont": {
  "website": false,
  "css": {
    "output": "./src/scss/components/",
+   "fileName": "_icons",
+    "cssPath": "../fonts/icons/",
    "include": "\\.(scss)$"
  },
  "emptyDist": true
},


```

**Comment by claudiuTicu** [comment]
Thank you very much

**Comment by jaywcjlove** [comment]
Supports `.svgtofontc` Configuration File.

```js
{
  "src": "./icon",
  "dist": "./fonts",
  "fontName": "svgtofont",
  "css": true
}
```

Upgrade `v3.16.3`
